name: Demo
values:
  - key: baseUrl
    value: 'https://cfb83526-155a-4628-8a55-3c8057eb4714.mock.pstmn.io'
  - key: INVENTORY_BASE_URL
    value: 'https://dab6c24a-6e01-40d2-9f34-0fd8436557e8.mock.pstmn.io'
