name: Automated API tests using Postman CLI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: '40 9 * * 1-5'

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Lint API Spec
        run: |
          postman spec lint "4dacd56d-084a-4096-8c0e-7de6b54ce9c6" \
            --workspace-id 0453f11a-88e7-4bdb-b744-5dd4a5db11d0 \
            --fail-severity error --output json --report-events
      - name: Run API tests
        run: |
          postman collection run "52509354-b38fa98f-8cc0-4bb6-92b8-83e4f932a9b3" \
            -e "52509354-c9ef7e0b-1614-461a-b43d-73d27eb5dab4" --report-events
