name: Automated API tests using Postman CLI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: '40 9 * * 1-5'

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Lint API Spec
        run: |
          postman spec lint "236747fb-3cf4-44d8-8878-01742d398fe0" \
            --workspace-id af5009a6-9406-4456-880e-4752ec632185 \
            --fail-severity error --output json --report-events
      - name: Run API tests
        run: |
          postman collection run "52509354-0487476e-cfea-454c-b2c0-d1d2db2b2916" \
            -e "52509354-332bc9e4-c48e-4f8a-9a7a-0fb2c3289add" --report-events
